#include "xlsone/core/license_manager.hpp"

#include "xlsone/core/obfuscation.hpp"

#include "ed25519/monocypher-ed25519.h"

#include <QCryptographicHash>
#include <QDateTime>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QProcess>
#include <QSettings>
#include <QSet>
#include <QSysInfo>
#include <QTimer>
#include <algorithm>

namespace xlsone {

static constexpr int kServerOutageGraceDays = 3;
static constexpr int kPostExpirationGraceDays = 7;
static constexpr int kClockRollbackToleranceSecs = 60 * 60;
static constexpr int kRestrictedModeMaxFiles = 3;
static const QString kTokenKey = QStringLiteral("license/token");
static const QString kOfflineTokenKey = QStringLiteral("license/offline");
static const QString kLastSeenUtcKey = QStringLiteral("license/lastSeenUtc");
static const QString kClockErrorMessage = QStringLiteral("系统时间异常，请校准系统时间后重试");

#if defined(Q_OS_LINUX)
// Built-in Linux license, signed offline with the same Ed25519 private key as
// server-issued licenses (rotation of 2026-07-17).  The payload is
// reconstructed below and must match the signed bytes exactly:
// {"key_id":"LINUX-BUILTIN","plan":"personal_lifetime","device_hash":"","device_components":[],"issued_at":1784264344,"expires_at":0}
static constexpr qint64 kLinuxBuiltinLicenseIssuedAt = 1784264344;
static const char kLinuxBuiltinLicenseSignature[] =
    "I1EQuvcw4hgggw22KGRW2bAOZQVd4wUuX2QJxq-kKSOZK4FzAD2UEJpg_qRNNK9HIjJCf0GYAMFDeJrI4NmjCw";
#endif

// Process-level cache for the device fingerprint to avoid repeated WMIC/PowerShell calls.
static QString g_deviceFingerprintCache;

// The Ed25519 public key and activation base URL are stored in
// obfuscated_secrets.cpp (generated by scripts/generate_obfuscation.py) and
// decrypted at runtime when XLSONE_OBFUSCATE is enabled.  This keeps the
// plaintext key and service endpoints out of the release binary's .rodata.

#ifndef XLSONE_OBFUSCATE
// Ed25519 public key (32 bytes) for verifying Windows license signatures.
// Must correspond to the private seed held ONLY in the Worker secret
// ED25519_PRIVATE_KEY.  This array is only compiled into non-obfuscated builds.
// Rotated 2026-07-17 after the previous seed leaked into the git history.
static constexpr uint8_t kLicensePublicKey[32] = {
    0xb0, 0xaf, 0x99, 0x04, 0x7c, 0xf3, 0x0b, 0x4f,
    0xe7, 0x23, 0x60, 0xd5, 0x3f, 0xf5, 0x76, 0x5c,
    0x3c, 0xcd, 0x33, 0xd9, 0x11, 0xe2, 0xb1, 0xf1,
    0x9b, 0x99, 0xdc, 0xd4, 0xc8, 0xff, 0x83, 0xcc
};
#endif // !XLSONE_OBFUSCATE

namespace {

QByteArray base64UrlDecodeBytes(const QString& base64url)
{
    QString s = base64url;
    s.replace(QLatin1Char('-'), QLatin1Char('+'))
     .replace(QLatin1Char('_'), QLatin1Char('/'));
    while (s.length() % 4) {
        s.append(QLatin1Char('='));
    }
    return QByteArray::fromBase64(s.toUtf8());
}

QString bytesToHex(const QByteArray& bytes)
{
    return QString::fromLatin1(bytes.toHex());
}

QByteArray sha256(const QByteArray& data)
{
    return QCryptographicHash::hash(data, QCryptographicHash::Sha256);
}

LicensePlan planFromString(const QString& plan)
{
    if (plan == QStringLiteral("enterprise_10")) {
        return LicensePlan::Enterprise10;
    }
    if (plan == QStringLiteral("personal_yearly")) {
        return LicensePlan::PersonalYearly;
    }
    if (plan == QStringLiteral("trial")) {
        return LicensePlan::Trial;
    }
    return LicensePlan::PersonalLifetime;
}

int remainingDaysUntil(const QDateTime& until)
{
    if (!until.isValid()) {
        return 0;
    }
    const qint64 seconds = QDateTime::currentDateTimeUtc().secsTo(until);
    if (seconds <= 0) {
        return 0;
    }
    return static_cast<int>((seconds + 24 * 60 * 60 - 1) / (24 * 60 * 60));
}

QDateTime settingsDateTimeUtc(const QString& key)
{
    const QDateTime value = QSettings().value(key).toDateTime();
    return value.isValid() ? value.toUTC() : QDateTime();
}

bool clockRollbackDetected(const QDateTime& nowUtc)
{
    const QDateTime lastSeenUtc = settingsDateTimeUtc(kLastSeenUtcKey);
    return lastSeenUtc.isValid()
        && nowUtc.addSecs(kClockRollbackToleranceSecs) < lastSeenUtc;
}

void updateLastSeenUtc(const QDateTime& nowUtc)
{
    QSettings settings;
    const QDateTime lastSeenUtc = settings.value(kLastSeenUtcKey).toDateTime();
    if (!lastSeenUtc.isValid() || nowUtc > lastSeenUtc.toUTC()) {
        settings.setValue(kLastSeenUtcKey, nowUtc);
    }
}

QByteArray canonicalPayloadJson(const QJsonObject& obj)
{
    const QString keyId = obj.value(QStringLiteral("key_id")).toString();
    const QString plan = obj.value(QStringLiteral("plan")).toString();
    const QString deviceHash = obj.value(QStringLiteral("device_hash")).toString();
    const QJsonArray deviceComponents = obj.value(QStringLiteral("device_components")).toArray();
    const qint64 issuedAt = static_cast<qint64>(obj.value(QStringLiteral("issued_at")).toDouble());
    const qint64 expiresAt = static_cast<qint64>(obj.value(QStringLiteral("expires_at")).toDouble());

    QStringList compParts;
    for (const QJsonValue& v : deviceComponents) {
        compParts.append(QStringLiteral("\"") + v.toString() + QStringLiteral("\""));
    }

    const QString payloadJsonString = QStringLiteral("{\"key_id\":\"%1\",\"plan\":\"%2\",\"device_hash\":\"%3\",\"device_components\":[%4],\"issued_at\":%5,\"expires_at\":%6}")
        .arg(keyId)
        .arg(plan)
        .arg(deviceHash)
        .arg(compParts.join(QLatin1Char(',')))
        .arg(issuedAt)
        .arg(expiresAt);
    return payloadJsonString.toUtf8();
}

#if defined(Q_OS_WIN)
QString runPowerShellCommand(const QString& script)
{
    QProcess process;
    process.start(QStringLiteral("powershell.exe"),
                  QStringList{ QStringLiteral("-NoProfile"),
                               QStringLiteral("-Command"),
                               script });
    if (!process.waitForFinished(5000)) {
        process.kill();
        return QString();
    }
    QString output = QString::fromLocal8Bit(process.readAllStandardOutput());
    return output.trimmed();
}

QString runWmicCommand(const QString& className, const QString& property)
{
    QProcess process;
    process.start(QStringLiteral("wmic"),
                  QStringList{ className, QStringLiteral("get"), property });
    if (!process.waitForFinished(5000)) {
        process.kill();
        return QString();
    }
    QString output = QString::fromLocal8Bit(process.readAllStandardOutput());
    // WMIC output has a header line followed by the value
    QStringList lines = output.split(QLatin1Char('\n'), Qt::SkipEmptyParts);
    if (lines.size() >= 2) {
        return lines.at(1).trimmed();
    }
    return QString();
}

QString readMachineGuid()
{
    QSettings settings(QStringLiteral("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Cryptography"),
                       QSettings::NativeFormat);
    return settings.value(QStringLiteral("MachineGuid")).toString().trimmed();
}
#endif // Q_OS_WIN

QString normalizeHardwareValue(const QString& value)
{
    QString cleaned = value.toUpper().trimmed();
    // Remove common placeholder/noise strings
    static const QStringList placeholders = {
        QStringLiteral("TO BE FILLED BY O.E.M."),
        QStringLiteral("NONE"),
        QStringLiteral("NOT AVAILABLE"),
        QStringLiteral("BASEBOARD SERIAL NUMBER"),
        QStringLiteral("SERIALNUMBER"),
    };
    for (const QString& p : placeholders) {
        if (cleaned == p) {
            return QString();
        }
    }
    return cleaned;
}

struct HardwareComponents {
    QString baseboardSerial;
    QString cpuId;
    QString diskSerial;
    QString machineGuid;

    QStringList nonEmptyValues() const
    {
        QStringList values;
        if (!baseboardSerial.isEmpty()) values << baseboardSerial;
        if (!cpuId.isEmpty()) values << cpuId;
        if (!diskSerial.isEmpty()) values << diskSerial;
        if (!machineGuid.isEmpty()) values << machineGuid;
        return values;
    }

    QStringList componentHashes() const
    {
        QStringList hashes;
        if (!baseboardSerial.isEmpty())
            hashes << bytesToHex(sha256(baseboardSerial.toUtf8()));
        if (!cpuId.isEmpty())
            hashes << bytesToHex(sha256(cpuId.toUtf8()));
        if (!diskSerial.isEmpty())
            hashes << bytesToHex(sha256(diskSerial.toUtf8()));
        if (!machineGuid.isEmpty())
            hashes << bytesToHex(sha256(machineGuid.toUtf8()));
        return hashes;
    }

    QString fullHash() const
    {
        QStringList values = nonEmptyValues();
        std::sort(values.begin(), values.end());
        if (values.isEmpty()) {
            return QString();
        }
        return bytesToHex(sha256(values.join(QLatin1Char('|')).toUtf8()));
    }
};

HardwareComponents collectWindowsComponents()
{
    HardwareComponents comp;
#if defined(Q_OS_WIN)
    comp.baseboardSerial = normalizeHardwareValue(
        runPowerShellCommand(QStringLiteral("(Get-CimInstance Win32_BaseBoard).SerialNumber")));
    if (comp.baseboardSerial.isEmpty()) {
        comp.baseboardSerial = normalizeHardwareValue(runWmicCommand(QStringLiteral("baseboard"),
                                                                      QStringLiteral("serialnumber")));
    }

    comp.cpuId = normalizeHardwareValue(
        runPowerShellCommand(QStringLiteral("(Get-CimInstance Win32_Processor).ProcessorId")));
    if (comp.cpuId.isEmpty()) {
        comp.cpuId = normalizeHardwareValue(runWmicCommand(QStringLiteral("cpu"),
                                                            QStringLiteral("processorid")));
    }

    comp.diskSerial = normalizeHardwareValue(
        runPowerShellCommand(QStringLiteral("(Get-CimInstance Win32_DiskDrive).SerialNumber")));
    if (comp.diskSerial.isEmpty()) {
        comp.diskSerial = normalizeHardwareValue(runWmicCommand(QStringLiteral("diskdrive"),
                                                                 QStringLiteral("serialnumber")));
    }

    comp.machineGuid = normalizeHardwareValue(readMachineGuid());
#endif
    return comp;
}

} // anonymous namespace

// ========== LicenseManager ==========

LicenseManager::LicenseManager(QObject* parent)
    : QObject(parent)
    , networkManager_(new QNetworkAccessManager(this))
{
    connect(networkManager_, &QNetworkAccessManager::finished,
            this, &LicenseManager::onActivationReply);
    loadPersistedState();
}

LicenseManager::~LicenseManager() = default;

LicenseState LicenseManager::state() const
{
    return state_;
}

LicenseInfo LicenseManager::currentInfo() const
{
    return currentInfo_;
}

bool LicenseManager::isFullyLicensed() const
{
    if (state_ == LicenseState::Activated) {
        return true;
    }
    if (state_ == LicenseState::Trial) {
        return checkTrial() > 0;
    }
    if (state_ == LicenseState::Expired) {
        return isInGracePeriod();
    }
    return false;
}

bool LicenseManager::isInGracePeriod() const
{
    if (state_ != LicenseState::Expired || !currentInfo_.expiresAt.isValid()) {
        return false;
    }
    const qint64 secondsSinceExpiry = currentInfo_.expiresAt.secsTo(QDateTime::currentDateTimeUtc());
    return secondsSinceExpiry >= 0
        && secondsSinceExpiry < kPostExpirationGraceDays * 24 * 60 * 60;
}

bool LicenseManager::canUse(LicenseFeature feature) const
{
    switch (feature) {
    case LicenseFeature::ImportFiles:
        return true;
    case LicenseFeature::BatchExport:
        return true;
    case LicenseFeature::NoExportWatermark:
        return isFullyLicensed();
    }
    return false;
}

int LicenseManager::maxImportFiles() const
{
    return isFullyLicensed() ? INT_MAX : kRestrictedModeMaxFiles;
}

QString LicenseManager::exportWatermarkText() const
{
    if (canUse(LicenseFeature::NoExportWatermark)) {
        return QString();
    }
    if (state_ == LicenseState::Expired) {
        return tr("授权已过期 — xlsOne");
    }
    return tr("未激活试用版 — xlsOne");
}

QString LicenseManager::restrictionMessage() const
{
    if (isFullyLicensed()) {
        return QString();
    }
    if (isInGracePeriod()) {
        return tr("授权已过期，宽限期内仍可全功能使用 %1 天。").arg(graceRemainingDays());
    }
    if (state_ == LicenseState::Expired) {
        return tr("授权已过期，每次最多处理 %1 个文件，导出将带水印。请激活以解除限制。")
            .arg(kRestrictedModeMaxFiles);
    }
    return tr("未激活，每次最多处理 %1 个文件，导出将带水印。可申请 14 天免费试用或输入激活码。")
        .arg(kRestrictedModeMaxFiles);
}

int LicenseManager::checkTrial() const
{
    if (currentInfo_.plan != LicensePlan::Trial || !currentInfo_.expiresAt.isValid()) {
        return -1;
    }

    const qint64 seconds = QDateTime::currentDateTimeUtc().secsTo(currentInfo_.expiresAt);
    if (seconds <= 0) {
        return -1;
    }
    return static_cast<int>((seconds + 24 * 60 * 60 - 1) / (24 * 60 * 60));
}

int LicenseManager::graceRemainingDays() const
{
    if (!currentInfo_.expiresAt.isValid()) {
        return 0;
    }
    const QDateTime nowUtc = QDateTime::currentDateTimeUtc();
    if (nowUtc <= currentInfo_.expiresAt) {
        return 0;
    }
    return remainingDaysUntil(currentInfo_.expiresAt.addDays(kServerOutageGraceDays));
}

QString LicenseManager::deviceFingerprint()
{
    if (!g_deviceFingerprintCache.isEmpty()) {
        return g_deviceFingerprintCache;
    }

#if defined(Q_OS_WIN)
    const HardwareComponents comp = collectWindowsComponents();
    const QString full = comp.fullHash();
    if (!full.isEmpty()) {
        g_deviceFingerprintCache = full;
        return g_deviceFingerprintCache;
    }
#endif

    // Fallback to Qt's machine unique id (may be empty on some platforms).
    const QByteArray id = QSysInfo::machineUniqueId();
    if (!id.isEmpty()) {
        g_deviceFingerprintCache = bytesToHex(sha256(id));
        return g_deviceFingerprintCache;
    }
    return QString();
}

void LicenseManager::clearDeviceFingerprintCache()
{
    g_deviceFingerprintCache.clear();
}

QString LicenseManager::activationBaseUrl()
{
#ifdef XLSONE_OBFUSCATE
    return xlsone::obf::activationBaseUrl();
#else
    return QStringLiteral(XLSONE_ACTIVATION_BASE_URL);
#endif
}

void LicenseManager::requestTrial(const QString& deviceFingerprint)
{
    QJsonObject body;
    body[QStringLiteral("device_hash")] = deviceFingerprint;
    body[QStringLiteral("device_name")] = QSysInfo::machineHostName();

#if defined(Q_OS_WIN)
    const HardwareComponents comp = collectWindowsComponents();
    QJsonArray components;
    for (const QString& hash : comp.componentHashes()) {
        components.append(hash);
    }
    body[QStringLiteral("device_components")] = components;
#endif

    QNetworkRequest request{
#ifdef XLSONE_OBFUSCATE
        QUrl(xlsone::obf::activationBaseUrl() + XLSONE_OBF_STRING("/api/trial/windows"))
#else
        QUrl(QStringLiteral(XLSONE_ACTIVATION_BASE_URL "/api/trial/windows"))
#endif
    };
    request.setHeader(QNetworkRequest::ContentTypeHeader,
                      QVariant(QStringLiteral("application/json")));
    request.setRawHeader("Accept", "application/json");

    const QByteArray payload = QJsonDocument(body).toJson(QJsonDocument::Compact);
    auto* reply = networkManager_->post(request, payload);
    reply->setProperty("_request_kind", QStringLiteral("trial"));

    auto* timer = new QTimer(reply);
    timer->setSingleShot(true);
    reply->setProperty("_timer", QVariant::fromValue(timer));
    connect(timer, &QTimer::timeout, reply, &QNetworkReply::abort);
    timer->start(10000);
}

bool LicenseManager::applyLicenseFile(const QByteArray& licenseData,
                                      const QString& deviceFingerprint,
                                      LicenseInfo* info,
                                      QString* errorMessage)
{
    auto fail = [&](const QString& message) {
        if (errorMessage) {
            *errorMessage = message;
        }
        return false;
    };

    const QJsonDocument doc = QJsonDocument::fromJson(licenseData);
    if (!doc.isObject()) {
        return fail(QStringLiteral("授权文件格式无效"));
    }

    const QJsonObject obj = doc.object();
    const QString signatureBase64 = obj.value(QStringLiteral("signature")).toString();
    if (signatureBase64.isEmpty()) {
        return fail(QStringLiteral("授权文件缺少签名"));
    }

    // Build canonical payload JSON matching the server's signing format.
    // We avoid relying on QJsonDocument's field ordering/number formatting,
    // which can differ from the JSON library that created the signature.
    const QString keyId = obj.value(QStringLiteral("key_id")).toString();
    const QString plan = obj.value(QStringLiteral("plan")).toString();
    const QString deviceHash = obj.value(QStringLiteral("device_hash")).toString();
    const qint64 issuedAt = static_cast<qint64>(obj.value(QStringLiteral("issued_at")).toDouble());
    const qint64 expiresAt = static_cast<qint64>(obj.value(QStringLiteral("expires_at")).toDouble());

    const QByteArray payloadJson = canonicalPayloadJson(obj);

    // Verify Ed25519 signature.
    const QByteArray signature = base64UrlDecodeBytes(signatureBase64);
    if (signature.size() != 64) {
        return fail(QStringLiteral("授权签名格式无效"));
    }
    if (!verifyEd25519Signature(payloadJson, signature)) {
        return fail(QStringLiteral("授权签名验证失败"));
    }

    // Check device binding.
    const QString storedFullHash = deviceHash;
    if (!storedFullHash.isEmpty() && !checkDeviceHash(obj, deviceFingerprint)) {
        return fail(QStringLiteral("授权文件与当前设备不匹配"));
    }

    const QDateTime nowUtc = QDateTime::currentDateTimeUtc();
    if (clockRollbackDetected(nowUtc)) {
        return fail(kClockErrorMessage);
    }

    const QDateTime issuedAtTime = issuedAt > 0
        ? QDateTime::fromSecsSinceEpoch(issuedAt).toUTC()
        : QDateTime();
    if (issuedAtTime.isValid() &&
        issuedAtTime > nowUtc.addSecs(kClockRollbackToleranceSecs)) {
        return fail(kClockErrorMessage);
    }

    // Check expiry. A short grace window protects existing users when the
    // activation service is unavailable around renewal time.
    QDateTime expiry;
    if (expiresAt > 0) {
        expiry = QDateTime::fromSecsSinceEpoch(expiresAt).toUTC();
        if (expiry <= nowUtc && expiry.addDays(kServerOutageGraceDays) <= nowUtc) {
            return fail(QStringLiteral("授权已过期"));
        }
    }

    LicenseInfo parsedInfo;
    parsedInfo.keyId = keyId;
    parsedInfo.plan = planFromString(plan);
    parsedInfo.deviceHash = storedFullHash;
    parsedInfo.issuedAt = issuedAtTime;
    parsedInfo.expiresAt = expiry;
    parsedInfo.rawPayload = payloadJson;
    if (info) {
        *info = parsedInfo;
    }
    currentInfo_ = parsedInfo;

    // Persist the validated license.
    QSettings settings;
    settings.setValue(kTokenKey, QString::fromUtf8(licenseData));
    settings.setValue(kOfflineTokenKey, QString::fromUtf8(licenseData));
    updateLastSeenUtc(nowUtc);
    setState(parsedInfo.plan == LicensePlan::Trial ? LicenseState::Trial : LicenseState::Activated);
    return true;
}

void LicenseManager::activate(const QString& key, const QString& deviceFingerprint)
{
    QJsonObject body;
    body[QStringLiteral("key")] = key;
    body[QStringLiteral("device_hash")] = deviceFingerprint;
    body[QStringLiteral("device_name")] = QSysInfo::machineHostName();

#if defined(Q_OS_WIN)
    const HardwareComponents comp = collectWindowsComponents();
    QJsonArray components;
    for (const QString& hash : comp.componentHashes()) {
        components.append(hash);
    }
    body[QStringLiteral("device_components")] = components;
#endif

    QNetworkRequest request{
#ifdef XLSONE_OBFUSCATE
        QUrl(xlsone::obf::activationBaseUrl() + XLSONE_OBF_STRING("/api/activate/windows"))
#else
        QUrl(QStringLiteral(XLSONE_ACTIVATION_BASE_URL "/api/activate/windows"))
#endif
    };
    request.setHeader(QNetworkRequest::ContentTypeHeader,
                      QVariant(QStringLiteral("application/json")));
    request.setRawHeader("Accept", "application/json");

    QByteArray payload = QJsonDocument(body).toJson(QJsonDocument::Compact);
    auto* reply = networkManager_->post(request, payload);
    reply->setProperty("_request_kind", QStringLiteral("activation"));

    auto* timer = new QTimer(reply);
    timer->setSingleShot(true);
    reply->setProperty("_timer", QVariant::fromValue(timer));
    connect(timer, &QTimer::timeout, reply, &QNetworkReply::abort);
    timer->start(10000);
}

bool LicenseManager::importOfflineLicenseFile(const QString& path,
                                              const QString& deviceFingerprint,
                                              QString* errorMessage)
{
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        if (errorMessage) {
            *errorMessage = QStringLiteral("无法读取授权文件");
        }
        return false;
    }

    const QByteArray data = file.readAll();
    file.close();

    return applyLicenseFile(data, deviceFingerprint, nullptr, errorMessage);
}

bool LicenseManager::verifyEd25519Signature(const QByteArray& message,
                                            const QByteArray& signature) const
{
    if (signature.size() != 64) {
        return false;
    }
    return crypto_ed25519_check(
        reinterpret_cast<const uint8_t*>(signature.constData()),
#ifdef XLSONE_OBFUSCATE
        xlsone::obf::licensePublicKey().data(),
#else
        kLicensePublicKey,
#endif
        reinterpret_cast<const uint8_t*>(message.constData()),
        static_cast<size_t>(message.size())) == 0;
}

bool LicenseManager::checkDeviceHash(const QJsonObject& licenseObj,
                                     const QString& actualFingerprint) const
{
    const QString expectedHash = licenseObj.value(QStringLiteral("device_hash")).toString();
    if (expectedHash.isEmpty()) {
        return true;
    }

    // Exact match first.
    if (expectedHash == actualFingerprint) {
        return true;
    }

    // Partial matching: allow hardware changes if enough components still match.
    const QJsonArray storedComponentsArray = licenseObj.value(QStringLiteral("device_components")).toArray();
    if (storedComponentsArray.isEmpty()) {
        return false;
    }

    QSet<QString> storedHashes;
    for (const QJsonValue& value : storedComponentsArray) {
        const QString hash = value.toString();
        if (!hash.isEmpty()) {
            storedHashes.insert(hash);
        }
    }
    if (storedHashes.isEmpty()) {
        return false;
    }

    const int storedCount = storedHashes.size();
    const int threshold = std::max(2, (storedCount * 2 + 2) / 3); // ceil(2/3)

#if defined(Q_OS_WIN)
    const HardwareComponents comp = collectWindowsComponents();
    const QStringList currentHashes = comp.componentHashes();
#else
    const QStringList currentHashes{ actualFingerprint };
#endif

    int matchCount = 0;
    for (const QString& hash : currentHashes) {
        if (storedHashes.contains(hash)) {
            ++matchCount;
        }
    }

    return matchCount >= threshold;
}

bool LicenseManager::parseVerifiedLicenseInfo(const QByteArray& licenseData,
                                              const QString& fingerprint,
                                              LicenseInfo* info)
{
    const QJsonDocument doc = QJsonDocument::fromJson(licenseData);
    if (!doc.isObject()) {
        return false;
    }
    const QJsonObject obj = doc.object();
    const QString sigB64 = obj.value(QStringLiteral("signature")).toString();
    if (sigB64.isEmpty()) {
        return false;
    }
    const QByteArray payloadJson = canonicalPayloadJson(obj);
    const QByteArray sig = base64UrlDecodeBytes(sigB64);
    if (sig.size() != 64) {
        return false;
    }

    // We need an instance to call the non-static verification helpers.
    // A temporary LicenseManager with no parent is sufficient because these
    // helpers do not access member state.
    LicenseManager temp(nullptr);
    if (!temp.verifyEd25519Signature(payloadJson, sig)) {
        return false;
    }
    if (!temp.checkDeviceHash(obj, fingerprint)) {
        return false;
    }

    const qint64 issuedAt = static_cast<qint64>(
        obj.value(QStringLiteral("issued_at")).toDouble());
    const qint64 expiresAt = static_cast<qint64>(
        obj.value(QStringLiteral("expires_at")).toDouble());

    info->keyId = obj.value(QStringLiteral("key_id")).toString();
    info->plan = planFromString(obj.value(QStringLiteral("plan")).toString());
    info->deviceHash = obj.value(QStringLiteral("device_hash")).toString();
    info->issuedAt = issuedAt > 0
        ? QDateTime::fromSecsSinceEpoch(issuedAt).toUTC()
        : QDateTime();
    info->expiresAt = expiresAt > 0
        ? QDateTime::fromSecsSinceEpoch(expiresAt).toUTC()
        : QDateTime();
    info->rawPayload = payloadJson;
    return true;
}

void LicenseManager::onActivationReply(QNetworkReply* reply)
{
    reply->deleteLater();

    if (auto* timer = qvariant_cast<QTimer*>(reply->property("_timer"))) {
        timer->stop();
    }

    const bool isTrialRequest =
        reply->property("_request_kind").toString() == QStringLiteral("trial");
    ActivationResult result;
    result.trial = isTrialRequest;

    if (reply->error() != QNetworkReply::NoError) {
        result.success = false;
        const QString errorString = reply->errorString();
        if (errorString.isEmpty()) {
            result.errorMessage = isTrialRequest
                ? QStringLiteral("暂时无法连接试用服务器，请稍后重试")
                : QStringLiteral("网络连接失败，请检查网络");
        } else {
            result.errorMessage = isTrialRequest
                ? QStringLiteral("暂时无法连接试用服务器: %1").arg(errorString)
                : QStringLiteral("网络错误: %1").arg(errorString);
        }
        emit activationFinished(result);
        return;
    }

    const int statusCode = reply->attribute(
        QNetworkRequest::HttpStatusCodeAttribute).toInt();
    const QByteArray body = reply->readAll();
    const QJsonDocument doc = QJsonDocument::fromJson(body);

    if (statusCode != 200 || !doc.isObject()) {
        result.success = false;
        if (doc.isObject()) {
            const QJsonObject obj = doc.object();
            const QString error = obj.value(QStringLiteral("error")).toString();
            if (error == QStringLiteral("KEY_NOT_FOUND"))
                result.errorMessage = QStringLiteral("激活码不存在");
            else if (error == QStringLiteral("KEY_REVOKED"))
                result.errorMessage = QStringLiteral("激活码已被吊销");
            else if (error == QStringLiteral("EXHAUSTED"))
                result.errorMessage = QStringLiteral("该激活码的激活次数已用尽（最多 3 台设备），请购买新的激活码");
            else if (error == QStringLiteral("SUBSCRIPTION_EXPIRED"))
                result.errorMessage = QStringLiteral("该激活码已过期，请购买新的激活码");
            else if (error == QStringLiteral("DEVICE_LIMIT"))
                result.errorMessage = QStringLiteral("已达到最大设备数限制");
            else if (error == QStringLiteral("DEVICE_MISMATCH"))
                result.errorMessage = QStringLiteral("授权文件与当前设备不匹配");
            else if (error == QStringLiteral("RATE_LIMITED"))
                result.errorMessage = QStringLiteral("请求过于频繁，请稍后再试");
            else if (error == QStringLiteral("TRIAL_EXPIRED")) {
                result.errorMessage = QStringLiteral("这台设备的免费试用已结束，请输入激活码继续使用完整功能");
                setState(LicenseState::Expired);
            }
            else if (error == QStringLiteral("TRIAL_UNAVAILABLE"))
                result.errorMessage = QStringLiteral("暂时无法启用试用，请稍后重试或输入激活码");
            else
                result.errorMessage = obj.value(QStringLiteral("message")).toString(
                    isTrialRequest ? QStringLiteral("试用启用失败") : QStringLiteral("激活失败"));
        } else {
            result.errorMessage = isTrialRequest
                ? QStringLiteral("试用启用失败: HTTP %1").arg(statusCode)
                : QStringLiteral("激活失败: HTTP %1").arg(statusCode);
        }
        emit activationFinished(result);
        return;
    }

    const QJsonObject obj = doc.object();
    const QJsonObject licenseObj = obj.value(QStringLiteral("license")).toObject();
    if (licenseObj.isEmpty()) {
        result.success = false;
        result.errorMessage = isTrialRequest
            ? QStringLiteral("试用服务器响应异常")
            : QStringLiteral("服务器响应异常");
        emit activationFinished(result);
        return;
    }

    const QByteArray licenseData = QJsonDocument(licenseObj).toJson(QJsonDocument::Compact);
    const QString fingerprint = deviceFingerprint();
    QString verifyError;
    if (!applyLicenseFile(licenseData, fingerprint, nullptr, &verifyError)) {
        result.success = false;
        result.errorMessage = verifyError;
        emit activationFinished(result);
        return;
    }

    result.success = true;
    result.trial = (currentInfo_.plan == LicensePlan::Trial);
    emit activationFinished(result);
}

void LicenseManager::setState(LicenseState s)
{
    if (state_ != s) {
        state_ = s;
        emit stateChanged();
    }
}

void LicenseManager::loadPersistedState()
{
    QSettings settings;

    // Check for existing signed license file
    const QString licenseText = settings.value(kTokenKey).toString();
    if (!licenseText.isEmpty()) {
        const QByteArray licenseData = licenseText.toUtf8();
        const QString fingerprint = deviceFingerprint();
        LicenseInfo info;
        QString applyError;
        if (applyLicenseFile(licenseData, fingerprint, &info, &applyError)) {
            return;
        }
        if (applyError == kClockErrorMessage) {
            setState(LicenseState::Expired);
            return;
        }

        // If the license is expired but still cryptographically valid and bound
        // to this device, preserve the Expired state so the UI can show a clear
        // "expired" message and offer renewal instead of silently reverting to
        // "unactivated".
        LicenseInfo expiredInfo;
        if (parseVerifiedLicenseInfo(licenseData, fingerprint, &expiredInfo) &&
            expiredInfo.expiresAt.isValid() &&
            expiredInfo.expiresAt <= QDateTime::currentDateTimeUtc()) {
            currentInfo_ = expiredInfo;
            setState(LicenseState::Expired);
            return;
        }

        // Invalid or tampered stored license: clear it.
        settings.remove(kTokenKey);
        settings.remove(kOfflineTokenKey);
    }

    // Linux builds fall back to a built-in Ed25519-signed license: the grant
    // only happens when the embedded signature verifies against the public
    // key, so it cannot be toggled via QSettings or a patched flag.
    if (loadOrCreateLinuxDefaultLicense()) {
        return;
    }

    setState(LicenseState::Unactivated);
}

bool LicenseManager::loadOrCreateLinuxDefaultLicense()
{
#if !defined(Q_OS_LINUX)
    return false;
#else
    // Linux builds are free, but the grant is cryptographic, not a flag: the
    // built-in license below is only honored when its Ed25519 signature
    // verifies against the embedded public key.  Rebuild the exact canonical
    // payload that was signed offline (see the constants at the top of this
    // file) and verify it like any server-issued license.
    QJsonObject obj;
    obj.insert(QStringLiteral("key_id"), QStringLiteral("LINUX-BUILTIN"));
    obj.insert(QStringLiteral("plan"), QStringLiteral("personal_lifetime"));
    obj.insert(QStringLiteral("device_hash"), QString());
    obj.insert(QStringLiteral("device_components"), QJsonArray());
    obj.insert(QStringLiteral("issued_at"),
               static_cast<double>(kLinuxBuiltinLicenseIssuedAt));
    obj.insert(QStringLiteral("expires_at"), 0.0);

    const QByteArray payloadJson = canonicalPayloadJson(obj);
    const QByteArray signature = base64UrlDecodeBytes(
        QString::fromLatin1(kLinuxBuiltinLicenseSignature));
    if (signature.size() != 64 || !verifyEd25519Signature(payloadJson, signature)) {
        return false;
    }

    currentInfo_.keyId = QStringLiteral("LINUX-BUILTIN");
    currentInfo_.plan = LicensePlan::PersonalLifetime;
    currentInfo_.deviceHash = deviceFingerprint();
    currentInfo_.issuedAt =
        QDateTime::fromSecsSinceEpoch(kLinuxBuiltinLicenseIssuedAt).toUTC();
    currentInfo_.expiresAt = QDateTime(); // lifetime
    currentInfo_.rawPayload = payloadJson;
    setState(LicenseState::Activated);
    return true;
#endif
}

} // namespace xlsone
