// Auto-generated by scripts/generate_obfuscation.py.
// Do not edit manually.  Regenerate when the public key or base URLs change.

#include "xlsone/core/obfuscation.hpp"

#include <algorithm>
#include <array>
#include <cstdint>
#include <QString>

namespace xlsone {
namespace obf {
namespace {

#ifdef XLSONE_OBFUSCATE

constexpr std::array<uint8_t, 32> kEncryptedLicensePublicKey = {
    0x2d, 0x73, 0x10, 0x7a, 0x99, 0xea, 0x49, 0x48,
    0x1e, 0x57, 0x23, 0x2d, 0x18, 0xac, 0xf4, 0x0d,
    0x49, 0x6f, 0x4e, 0xd2, 0xca, 0x77, 0x21, 0xb9,
    0x66, 0x3b, 0x5e, 0xad, 0x9a, 0x02, 0x27, 0x52,
};

constexpr std::array<uint8_t, 22> kEncryptedActivationBaseUrl = {
    0xe9, 0xc5, 0x6d, 0xf1, 0x3e, 0x39, 0x87, 0xff,
    0xb6, 0x6d, 0xa5, 0x7c, 0xa3, 0x3a, 0x28, 0x26,
    0xdf, 0x04, 0x47, 0x32, 0xf2, 0x1e,
};

constexpr std::array<uint8_t, 18> kEncryptedUpdateBaseUrl = {
    0xe9, 0xc5, 0x6d, 0xf1, 0x3e, 0x39, 0x87, 0xff,
    0xad, 0x30, 0xbc, 0x27, 0xb7, 0x25, 0x3e, 0x67,
    0xd2, 0x0f,
};

#else // !XLSONE_OBFUSCATE

static constexpr uint8_t kPlainLicensePublicKey[32] = { 0xac, 0xc2, 0x09, 0xfb, 0xd4, 0xe9, 0xe1, 0x98, 0xc9, 0x4a, 0xef, 0x7f, 0xc3, 0xfa, 0xaf, 0x44, 0xf8, 0x0e, 0x27, 0x83, 0x57, 0x04, 0x59, 0x59, 0xe1, 0xd6, 0xa2, 0xaf, 0xb1, 0x04, 0x4c, 0xeb };

#endif // XLSONE_OBFUSCATE

} // namespace

std::array<uint8_t, 32> licensePublicKey()
{
#ifdef XLSONE_OBFUSCATE
    return detail::decryptByteArray(kEncryptedLicensePublicKey);
#else
    std::array<uint8_t, 32> out{};
    std::copy(kPlainLicensePublicKey, kPlainLicensePublicKey + 32, out.begin());
    return out;
#endif
}

QString activationBaseUrl()
{
#ifdef XLSONE_OBFUSCATE
    return detail::decryptString(kEncryptedActivationBaseUrl.data(), kEncryptedActivationBaseUrl.size());
#else
    return QStringLiteral("https://api.xlsone.com");
#endif
}

QString updateBaseUrl()
{
#ifdef XLSONE_OBFUSCATE
    return detail::decryptString(kEncryptedUpdateBaseUrl.data(), kEncryptedUpdateBaseUrl.size());
#else
    return QStringLiteral("https://z-pulse.cn");
#endif
}

} // namespace obf
} // namespace xlsone
