#!/usr/bin/env python3
"""Generate obfuscated_secrets.cpp for the xlsOne Qt build.

The generated file provides three getters used by the application:

    std::array<uint8_t, 32> xlsone::obf::licensePublicKey();
    QString xlsone::obf::activationBaseUrl();
    QString xlsone::obf::updateBaseUrl();

When XLSONE_OBFUSCATE is defined at compile time, the implementations decrypt
pre-encrypted arrays; the plaintext values are then NOT present in .rodata.
When XLSONE_OBFUSCATE is undefined, the implementations fall back to the
original plaintext literals so debugging and non-obfuscated builds are unaffected.

The XOR algorithm must stay in sync with xlsone::obf::detail in
obfuscation.hpp.

Typical usage from CMake:

    python3 scripts/generate_obfuscation.py \
        --public-key "<64-hex-public-key-from-secrets.json>" \
        --activation-url "https://api.xlsone.com" \
        --update-url "https://z-pulse.cn" \
        --output core/src/obfuscated_secrets.cpp

If --public-key is omitted, a placeholder all-zero key is emitted and a
warning comment is written into the generated file.
"""

import argparse
import sys
from typing import List, Optional, Tuple

_OBF_KEY = bytes([
    0x7a, 0x19, 0x4c, 0x83, 0xe2, 0x5f, 0xa1, 0x66,
    0xb4, 0x0d, 0x71, 0x38, 0xcc, 0x92, 0x2a, 0x57,
])


def _mix_index(i: int) -> int:
    return (i * 173 + 251) & 0xFF


def _encrypt_bytes(data: bytes) -> List[int]:
    return [b ^ _OBF_KEY[i % len(_OBF_KEY)] ^ _mix_index(i) for i, b in enumerate(data)]


def _format_array(values: List[int], width: int = 8) -> str:
    lines = []
    for i in range(0, len(values), width):
        row = ", ".join(f"0x{v:02x}" for v in values[i : i + width])
        lines.append("    " + row + ",")
    return "\n".join(lines)


def _parse_public_key(key_hex: Optional[str]) -> Tuple[bytes, bool]:
    if not key_hex:
        return bytes(32), False
    key_hex = key_hex.strip().replace("0x", "").replace(",", "").replace(" ", "")
    if len(key_hex) != 64:
        raise ValueError(f"Public key must be 32 bytes (64 hex chars), got {len(key_hex)}")
    try:
        return bytes.fromhex(key_hex), True
    except ValueError as exc:
        raise ValueError(f"Invalid hex public key: {exc}") from exc


def _c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Generate obfuscated secrets for xlsOne Qt")
    parser.add_argument("--public-key", default="", help="32-byte Ed25519 public key as 64 hex chars")
    parser.add_argument("--activation-url", default="https://api.xlsone.com", help="Activation API base URL")
    parser.add_argument("--update-url", default="https://z-pulse.cn", help="Update check base URL")
    parser.add_argument("--output", required=True, help="Output .cpp file path")
    args = parser.parse_args(argv)

    pub_key, has_real_key = _parse_public_key(args.public_key)
    enc_pub_key = _encrypt_bytes(pub_key)
    enc_activation = _encrypt_bytes(args.activation_url.encode("utf-8"))
    enc_update = _encrypt_bytes(args.update_url.encode("utf-8"))

    plain_pub_key_lines = ", ".join(f"0x{b:02x}" for b in pub_key)

    warning = ""
    if not has_real_key:
        warning = (
            "\n// WARNING: XLSONE_LICENSE_PUBLIC_KEY was not provided; "
            "the fallback key below is all zeros and will cause signature verification to fail.\n"
        )

    content = f"""// Auto-generated by scripts/generate_obfuscation.py.
// Do not edit manually.  Regenerate when the public key or base URLs change.{warning}

#include "xlsone/core/obfuscation.hpp"

#include <algorithm>
#include <array>
#include <cstdint>
#include <QString>

namespace xlsone {{
namespace obf {{
namespace {{

#ifdef XLSONE_OBFUSCATE

constexpr std::array<uint8_t, 32> kEncryptedLicensePublicKey = {{
{_format_array(enc_pub_key)}
}};

constexpr std::array<uint8_t, {len(enc_activation)}> kEncryptedActivationBaseUrl = {{
{_format_array(enc_activation)}
}};

constexpr std::array<uint8_t, {len(enc_update)}> kEncryptedUpdateBaseUrl = {{
{_format_array(enc_update)}
}};

#else // !XLSONE_OBFUSCATE

static constexpr uint8_t kPlainLicensePublicKey[32] = {{ {plain_pub_key_lines} }};

#endif // XLSONE_OBFUSCATE

}} // namespace

std::array<uint8_t, 32> licensePublicKey()
{{
#ifdef XLSONE_OBFUSCATE
    return detail::decryptByteArray(kEncryptedLicensePublicKey);
#else
    std::array<uint8_t, 32> out{{}};
    std::copy(kPlainLicensePublicKey, kPlainLicensePublicKey + 32, out.begin());
    return out;
#endif
}}

QString activationBaseUrl()
{{
#ifdef XLSONE_OBFUSCATE
    return detail::decryptString(kEncryptedActivationBaseUrl.data(), kEncryptedActivationBaseUrl.size());
#else
    return QStringLiteral("{_c_escape(args.activation_url)}");
#endif
}}

QString updateBaseUrl()
{{
#ifdef XLSONE_OBFUSCATE
    return detail::decryptString(kEncryptedUpdateBaseUrl.data(), kEncryptedUpdateBaseUrl.size());
#else
    return QStringLiteral("{_c_escape(args.update_url)}");
#endif
}}

}} // namespace obf
}} // namespace xlsone
"""

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
